-- 12.Create a function to return the total revenue generated 
-- per vendor (Manufacturer) every year in each segment(window)

DELIMITER $$

CREATE PROCEDURE totalRev_perVendor_segmentYear()
BEGIN
    SELECT
        DISTINCT
        Manufacturer.Manufacturer,
        YEAR(Orders.OrderDate) as yearo,
        CustomerSegment.CustomerSegmentName,
        SUM(OrderDetails.Sale)
     OVER (
        PARTITION BY 
            Manufacturer.Manufacturer,
            YEAR(Orders.OrderDate),
            CustomerSegment.CustomerSegmentName 
        ORDER BY YEAR(Orders.OrderDate) as total_rev -- Get the revenue generated by vendor, year , and segment
    )
    FROM
    Manufacturer
    LEFT JOIN Product
        ON Manufacturer.ManufacturerID = Product.ManufacturerId
    LEFT JOIN OrderDetails  -- we need to left join so we can access the Orders table
        ON Product.ProductId = OrderDetails.ProductId
    LEFT JOIN Orders 
        ON OrderDetails.POS_OrderKey = Orders.POS_OrderKey
    LEFT JOIN Customer -- we need to left join so we can access the CustomerSegment
        ON Customer.CustomerId = Orders.CustomerId
    LEFT JOIN CustomerSegment
        ON CustomerSegment.CustomerSegmentId = Customer.CustomerSegmentId ;
        
END$$
DELIMITER;
